In [1]:
# Load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.tools.plotting import scatter_matrix
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from IPython.display import display
from sklearn import preprocessing
from sklearn.decomposition import PCA
from __future__ import print_function
from sklearn.preprocessing import MinMaxScaler
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Load dataset 
url = "1.5_ML_Data_NC_fake_articles_2100.csv"
names = ["id","Labels","Class","WC","Analytic","Clout","Authentic","Tone","WPS","Sixltr","Dic","function","pronoun","ppron","i","we","you","shehe","they","ipron","article","prep","auxverb","adverb","conj","negate","verb","adj","compare","interrog","number","quant","affect","posemo","negemo","anx","anger","sad","social","family","friend","female","male","cogproc","insight","cause","discrep","tentat","certain","differ","percept","see","hear","feel","bio","body","health","sexual","ingest","drives","affiliation","achieve","power","reward","risk","focuspast","focuspresent","focusfuture","relativ","motion","space","time","work","leisure","home","money","relig","death","informal","swear","netspeak","assent","nonflu","filler","self_search_adult","self_search_medical","self_search_spoofed","self_search_violence","text_exist","max_score","score_red","score_green","score_blue","max_frac","frac_red","frac_green","frac_blue","no_of_faces","age","gender","gender_confidence","face_quality_brightness","face_quality_sharpness","smile","smile_confidence","emotion_happy","emotion_sad","emotion_angry","emotion_confused","emotion_disgusted","emotion_surprised","emotion_calm","emotion_unknown","no_of_celebrity_faces","celebrity_confidence","celebrity_quality_brightness","celebrity_quality_sharpness","size","width","height","sharpness","contrast","brightness","color_dominant_r","color_dominant_g","color_dominant_b","has_artificial","has_natural","topic_0","topic_1","topic_2","topic_3","topic_4","topic_5","topic_6","topic_7","topic_8","topic_9"]
dataset = pd.read_csv(url, names=names,low_memory=False,skiprows=[0])
print(dataset.shape)

(17961, 138)


In [4]:
fake_class_dataset = dataset.loc[dataset['Class'] == 'fake']
print(fake_class_dataset.shape)

(2073, 138)


In [5]:
credible_class_dataset = dataset.loc[dataset['Class'] == 'credible']
print(credible_class_dataset.shape)

(15888, 138)


In [6]:
credible_class_dataset_sampled = credible_class_dataset.sample(n=2073)
print(credible_class_dataset_sampled.shape)

(2073, 138)


In [ ]:
fake_class_dataset.to_csv('ML_Data_Sampled_Fake.csv')

In [7]:
final_dataset = pd.concat([fake_class_dataset, credible_class_dataset_sampled])
print(final_dataset.shape)
#final_dataset.to_csv('ML_Data_Sampled.csv')

(4146, 138)


In [ ]:
#array = final_dataset.values
#X_both = array[:,2:137]
#Y = array[:,0:2]

#std_scaler = MinMaxScaler().fit(X_both)
#X_both_scaled = std_scaler.transform(X_both)
#print(X_both_scaled.shape)
#print(Y.shape)

In [ ]:
#np.savetxt('ML_Data_Scaled_Sampled_1.csv',X_both_scaled,fmt='%.6f',delimiter=',',header='"WC","Analytic","Clout","Authentic","Tone","WPS","Sixltr","Dic","function","pronoun","ppron","i","we","you","shehe","they","ipron","article","prep","auxverb","adverb","conj","negate","verb","adj","compare","interrog","number","quant","affect","posemo","negemo","anx","anger","sad","social","family","friend","female","male","cogproc","insight","cause","discrep","tentat","certain","differ","percept","see","hear","feel","bio","body","health","sexual","ingest","drives","affiliation","achieve","power","reward","risk","focuspast","focuspresent","focusfuture","relativ","motion","space","time","work","leisure","home","money","relig","death","informal","swear","netspeak","assent","nonflu","filler","self_search_adult","self_search_medical","self_search_spoofed","self_search_violence","text_exist","max_score","score_red","score_green","score_blue","max_frac","frac_red","frac_green","frac_blue","no_of_faces","age","gender","gender_confidence","face_quality_brightness","face_quality_sharpness","smile","smile_confidence","emotion_happy","emotion_sad","emotion_angry","emotion_confused","emotion_disgusted","emotion_surprised","emotion_calm","emotion_unknown","no_of_celebrity_faces","celebrity_confidence","celebrity_quality_brightness","celebrity_quality_sharpness","size","width","height","sharpness","contrast","brightness","color_dominant_r","color_dominant_g","color_dominant_b","has_artificial","has_natural","topic_0","topic_1","topic_2","topic_3","topic_4","topic_5","topic_6","topic_7","topic_8","topic_9"')
#np.savetxt('ML_Data_Scaled_Sampled_2.csv',Y[:,0],fmt='%s',delimiter=',', header='"Labels"' )
#np.savetxt('ML_Data_Scaled_Sampled_3.csv',Y[:,1],fmt='%s',delimiter=',', header='"Class"' )
#new_array = np.concatenate((Y,X_both_scaled),axis = 1)
#print(new_array.shape)

In [ ]:
#final_dataset_scaled = pd.DataFrame(data=new_array)
#print(final_dataset_scaled.shape)
#final_dataset_scaled.to_csv('ML_Data_Sampled_Standardized.csv')

In [8]:
# Split-out validation dataset
array = final_dataset.values
X_text = array[:,3:84]
X_visual = array[:,84:138]
X_both = array[:,3:138]
Y = array[:,2]

print(array.shape)
print(X_text.shape)
print(X_visual.shape)
print(X_both.shape)

(4146, 138)
(4146, 81)
(4146, 54)
(4146, 135)


In [9]:
validation_size = 0.30
seed = 7

X_text_train, X_text_validation, Y_text_train, Y_text_validation = model_selection.train_test_split(X_text, Y, test_size=validation_size, random_state=seed)
X_visual_train, X_visual_validation, Y_visual_train, Y_visual_validation = model_selection.train_test_split(X_visual, Y, test_size=validation_size, random_state=seed)
X_both_train, X_both_validation, Y_both_train, Y_both_validation = model_selection.train_test_split(X_both, Y, test_size=validation_size, random_state=seed)
print(X_text_train.shape)
print(X_visual_train.shape)
print(X_both_train.shape)
print(Y_both_train.shape)

(2902, 81)
(2902, 54)
(2902, 135)
(2902,)


In [10]:
#std_scale = preprocessing.StandardScaler().fit(X_text_train)
#X_text_train = std_scale.transform(X_text_train)
#X_text_validation = std_scale.transform(X_text_validation)

std_scaler = MinMaxScaler().fit(X_text_train)
X_text_train = std_scaler.transform(X_text_train)
X_text_validation = std_scaler.transform(X_text_validation)

#std_scale = preprocessing.StandardScaler().fit(X_visual_train)
#X_visual_train = std_scale.transform(X_visual_train)
#X_visual_validation = std_scale.transform(X_visual_validation)

std_scaler = MinMaxScaler().fit(X_visual_train)
X_visual_train = std_scaler.transform(X_visual_train)
X_visual_validation = std_scaler.transform(X_visual_validation)

#std_scale = preprocessing.StandardScaler().fit(X_both_train)
#X_both_train = std_scale.transform(X_both_train)
#X_both_validation = std_scale.transform(X_both_validation)

std_scaler = MinMaxScaler().fit(X_both_train)
X_both_train = std_scaler.transform(X_both_train)
X_both_validation = std_scaler.transform(X_both_validation)

print(X_text_train.shape)
print(X_text_validation.shape)

(2902, 81)
(1244, 81)


In [11]:
# Test options and evaluation metric
seed = 7
scoring = 'accuracy'
def getProperDataForTraining(no):
    if(no == 0):
        return X_text_train, Y_text_train
    elif(no == 1):
        return X_visual_train, Y_visual_train
    else:
        return X_both_train, Y_both_train

In [13]:
# Spot Check Algorithms
models_at_each_i = []
model_with_text = []
model_with_visual = []
model_with_both = []

for i in range(3):
    print(i)
    training_x, training_y = getProperDataForTraining(i)
    models = []
    #models.append(('LR', LogisticRegression()))
    #models.append(('LDA', LinearDiscriminantAnalysis()))
    #models.append(('KNN', KNeighborsClassifier()))
    models.append(('CART', DecisionTreeClassifier()))
    #models.append(('NB', GaussianNB()))
    models.append(('SVM', SVC()))
    models.append(('RF', RandomForestClassifier()))
    # evaluate each model in turn
    results = []
    names = []
    for name, model in models:
        kfold = model_selection.KFold(n_splits=10, random_state=seed)
        cv_results = model_selection.cross_val_score(model, training_x, training_y, cv=kfold, scoring=scoring)
        #print(cv_results)
        results.append(cv_results)
        names.append(name)
        msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
        #print(msg)
        if(i == 0):
            model_with_text.append(cv_results.mean())
        elif(i == 1):
            model_with_visual.append(cv_results.mean())
        elif(i == 2):
            model_with_both.append(cv_results.mean())
    models_at_each_i.append(models)
print(model_with_text)
print(model_with_visual)
print(model_with_both)

0
1
2
[0.83701267922739642, 0.85664296717620569, 0.87904017063633122]
[0.98414741083066715, 0.74430738239127858, 0.94899751155350154]
[0.94589880317573183, 0.85802820239364852, 0.96451238298376585]


In [14]:
def getProperDataForValidation(no):
    if(no == 0):
        return X_text_validation, Y_text_validation
    elif(no == 1):
        return X_visual_validation, Y_visual_validation
    else:
        return X_both_validation, Y_both_validation

In [15]:
# Make predictions on validation dataset#store_covariance='true'
for i in range(3):
    print(i)
    training_x, training_y = getProperDataForTraining(i)
    validation_x, validation_y = getProperDataForValidation(i)
    dtc = DecisionTreeClassifier()
    dtc.fit(training_x, training_y)
    predictions_dtc = dtc.predict(validation_x)
    print("Iteration "+str(i+1))
    print(accuracy_score(validation_y, predictions_dtc))
    print(confusion_matrix(validation_y, predictions_dtc))
    print(classification_report(validation_y, predictions_dtc))

0
Iteration 1
0.833601286174
[[522  95]
 [112 515]]
             precision    recall  f1-score   support

   credible       0.82      0.85      0.83       617
       fake       0.84      0.82      0.83       627

avg / total       0.83      0.83      0.83      1244

1
Iteration 2
0.983118971061
[[608   9]
 [ 12 615]]
             precision    recall  f1-score   support

   credible       0.98      0.99      0.98       617
       fake       0.99      0.98      0.98       627

avg / total       0.98      0.98      0.98      1244

2
Iteration 3
0.934083601286
[[577  40]
 [ 42 585]]
             precision    recall  f1-score   support

   credible       0.93      0.94      0.93       617
       fake       0.94      0.93      0.93       627

avg / total       0.93      0.93      0.93      1244



In [16]:
# Make predictions on validation dataset#store_covariance='true'
for i in range(3):
    training_x, training_y = getProperDataForTraining(i)
    validation_x, validation_y = getProperDataForValidation(i)
    svc = SVC(probability=True)
    svc.fit(training_x, training_y)
    predictions_svc = svc.predict(validation_x)
    print("Iteration "+str(i+1))
    print(accuracy_score(validation_y, predictions_svc))
    print(confusion_matrix(validation_y, predictions_svc))
    print(classification_report(validation_y, predictions_svc))

Iteration 1
0.850482315113
[[538  79]
 [107 520]]
             precision    recall  f1-score   support

   credible       0.83      0.87      0.85       617
       fake       0.87      0.83      0.85       627

avg / total       0.85      0.85      0.85      1244

Iteration 2
0.716237942122
[[468 149]
 [204 423]]
             precision    recall  f1-score   support

   credible       0.70      0.76      0.73       617
       fake       0.74      0.67      0.71       627

avg / total       0.72      0.72      0.72      1244

Iteration 3
0.845659163987
[[541  76]
 [116 511]]
             precision    recall  f1-score   support

   credible       0.82      0.88      0.85       617
       fake       0.87      0.81      0.84       627

avg / total       0.85      0.85      0.85      1244



In [17]:
#store_covariance='true'
rf_models = []
rf_models_predictions_probabilities = []
for i in range(3):
    training_x, training_y = getProperDataForTraining(i)
    validation_x, validation_y = getProperDataForValidation(i)
    rf = RandomForestClassifier(n_estimators=250,random_state=0)
    rf.fit(training_x, training_y)
    predictions = rf.predict(validation_x)
    predictions_probability = rf.predict_proba(validation_x)
    rf_models.append(rf)
    rf_models_predictions_probabilities.append(predictions_probability)
    print("Iteration "+str(i+1))
    print(accuracy_score(validation_y, predictions))
    print(confusion_matrix(validation_y, predictions))
    print(classification_report(validation_y, predictions))

Iteration 1
0.909967845659
[[563  54]
 [ 58 569]]
             precision    recall  f1-score   support

   credible       0.91      0.91      0.91       617
       fake       0.91      0.91      0.91       627

avg / total       0.91      0.91      0.91      1244

Iteration 2
0.963826366559
[[579  38]
 [  7 620]]
             precision    recall  f1-score   support

   credible       0.99      0.94      0.96       617
       fake       0.94      0.99      0.96       627

avg / total       0.96      0.96      0.96      1244

Iteration 3
0.971061093248
[[586  31]
 [  5 622]]
             precision    recall  f1-score   support

   credible       0.99      0.95      0.97       617
       fake       0.95      0.99      0.97       627

avg / total       0.97      0.97      0.97      1244



In [ ]:
training_x, training_y = getProperDataForTraining(1)
validation_x, validation_y = getProperDataForValidation(1)
#print(validation_x[0])
num = 150
class_names = ['credible', 'fake']
indices_name = ["WC","Analytic","Clout","Authentic","Tone","WPS","Sixltr","Dic","function","pronoun","ppron","i","we","you","shehe","they","ipron","article","prep","auxverb","adverb","conj","negate","verb","adj","compare","interrog","number","quant","affect","posemo","negemo","anx","anger","sad","social","family","friend","female","male","cogproc","insight","cause","discrep","tentat","certain","differ","percept","see","hear","feel","bio","body","health","sexual","ingest","drives","affiliation","achieve","power","reward","risk","focuspast","focuspresent","focusfuture","relativ","motion","space","time","work","leisure","home","money","relig","death","informal","swear","netspeak","assent","nonflu","filler","self_search_adult","self_search_medical","self_search_spoofed","self_search_violence","text_exist","max_score","score_red","score_green","score_blue","max_frac","frac_red","frac_green","frac_blue","no_of_faces","age","gender","gender_confidence","face_quality_brightness","face_quality_sharpness","smile","smile_confidence","emotion_happy","emotion_sad","emotion_angry","emotion_confused","emotion_disgusted","emotion_surprised","emotion_calm","emotion_unknown","no_of_celebrity_faces","celebrity_confidence","celebrity_quality_brightness","celebrity_quality_sharpness","topic_0","topic_1","topic_2","topic_3","topic_4","topic_5","topic_6","topic_7","topic_8","topic_9"]
explainer = lime.lime_tabular.LimeTabularExplainer(training_x, feature_names=indices_name, class_names=class_names,
                                                   discretize_continuous=True)
exp = explainer.explain_instance(validation_x[num], rf_models[1].predict_proba, num_features=20, top_labels=1)
exp.show_in_notebook(show_table=True, show_all=False)

print('Document id: %d' % num)
print(rf_models_predictions_probabilities[1][num])
print('True class: %s' % validation_y[num])
exp.as_list()

In [ ]:
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(8,8)).clf()
model_name = ['Textual','Visual','Textual+Visual']
for idx in range(3):
    validation_x, validation_y = getProperDataForValidation(idx)
    true_prob_validation_y = label_binarize(validation_y, classes=['fake','credible'])
    predict_prob_validation_y = rf_models_predictions_probabilities[idx]
    positive_class_predict_prob_valid_y = predict_prob_validation_y[:,0]
    roc_score = roc_auc_score(true_prob_validation_y, positive_class_predict_prob_valid_y,average='micro')
    print(roc_score)
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    for i in range(1):
        fpr[i], tpr[i], _ = roc_curve(true_prob_validation_y, positive_class_predict_prob_valid_y)
        roc_auc[i] = auc(fpr[i], tpr[i])
    # Compute micro-average ROC curve and ROC area
    fpr["micro"], tpr["micro"], _ = roc_curve(true_prob_validation_y.ravel(), positive_class_predict_prob_valid_y.ravel())
    roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])
    print(roc_auc)
    lw = 2
    plt.plot(fpr["micro"], tpr["micro"], 
             #color='darkorange',
             lw=lw, label='%s - ROC curve (area = %0.2f)' % (model_name[idx], roc_auc[0]))
plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic example')
plt.legend(loc="lower right")
plt.show()

In [ ]:
#indices_name = ["WC","Analytic","Clout","Authentic","Tone","WPS","Sixltr","Dic","function","pronoun","ppron","i","we","you","shehe","they","ipron","article","prep","auxverb","adverb","conj","negate","verb","adj","compare","interrog","number","quant","affect","posemo","negemo","anx","anger","sad","social","family","friend","female","male","cogproc","insight","cause","discrep","tentat","certain","differ","percept","see","hear","feel","bio","body","health","sexual","ingest","drives","affiliation","achieve","power","reward","risk","focuspast","focuspresent","focusfuture","relativ","motion","space","time","work","leisure","home","money","relig","death","informal","swear","netspeak","assent","nonflu","filler"]
#indices_name = ["num_faces","white","american indian or alaska native","asian","hispanic or latino or spanish origin","middle eastern or north african","black or african american","native hawaiian or pacific islander","age","masculine","feminine","topic_0","topic_1","topic_2","topic_3","topic_4","topic_5","topic_6","topic_7","topic_8","topic_9"]
indices_name = ["WC","Analytic","Clout","Authentic","Tone","WPS","Sixltr","Dic","function","pronoun","ppron","i","we","you","shehe","they","ipron","article","prep","auxverb","adverb","conj","negate","verb","adj","compare","interrog","number","quant","affect","posemo","negemo","anx","anger","sad","social","family","friend","female","male","cogproc","insight","cause","discrep","tentat","certain","differ","percept","see","hear","feel","bio","body","health","sexual","ingest","drives","affiliation","achieve","power","reward","risk","focuspast","focuspresent","focusfuture","relativ","motion","space","time","work","leisure","home","money","relig","death","informal","swear","netspeak","assent","nonflu","filler","self_search_adult","self_search_medical","self_search_spoofed","self_search_violence","text_exist","max_score","score_red","score_green","score_blue","max_frac","frac_red","frac_green","frac_blue","no_of_faces","age","gender","gender_confidence","face_quality_brightness","face_quality_sharpness","smile","smile_confidence","emotion_happy","emotion_sad","emotion_angry","emotion_confused","emotion_disgusted","emotion_surprised","emotion_calm","emotion_unknown","no_of_celebrity_faces","celebrity_confidence","celebrity_quality_brightness","celebrity_quality_sharpness","size","width","height","sharpness","contrast","brightness","color_dominant_r","color_dominant_g","color_dominant_b","has_artificial","has_natural","topic_0","topic_1","topic_2","topic_3","topic_4","topic_5","topic_6","topic_7","topic_8","topic_9"]

In [ ]:
importances = rf_models[2].feature_importances_
std = np.std([tree.feature_importances_ for tree in rf.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

In [ ]:
# Print the feature ranking
indices_name_sorted = []
for f in range(len(indices_name)):
    #print("%d. %s (%f)" % (f + 1, indices_name[indices[f]], importances[indices[f]]))
    indices_name_sorted.append(indices_name[indices[f]])

In [ ]:
# Plot the feature importances of the forest
plt.figure(figsize=(30,10))
plt.title("Feature importances")
plt.bar(range(len(indices_name)), importances[indices],
       color="g", yerr=std[indices], align="center")
plt.xticks(range(len(indices_name)), indices_name_sorted,rotation=90)
plt.xlim([-1, len(indices_name)])
#fig.savefig('test.pdf')
plt.show()

# Make predictions on validation dataset
results
lr = LogisticRegression()#store_covariance='true'
lr.fit(X_train_std, Y_train)
predictions_lr = lr.predict(X_validation_std)
print(accuracy_score(Y_validation, predictions_lr))
print(confusion_matrix(Y_validation, predictions_lr))
print(classification_report(Y_validation, predictions_lr))

# Make predictions on validation dataset
lda = LinearDiscriminantAnalysis()#store_covariance='true'
lda.fit(X_train_std, Y_train)
predictions_lda = lda.predict(X_validation_std)
print(accuracy_score(Y_validation, predictions_lda))
print(confusion_matrix(Y_validation, predictions_lda))
print(classification_report(Y_validation, predictions_lda))

# Make predictions on validation dataset
nb = GaussianNB()#store_covariance='true'
nb.fit(X_train_std, Y_train)
predictions_nb = nb.predict(X_validation_std)
print(accuracy_score(Y_validation, predictions_nb))
print(confusion_matrix(Y_validation, predictions_nb))
print(classification_report(Y_validation, predictions_nb))

# Make predictions on validation dataset
knn = KNeighborsClassifier()#store_covariance='true'
knn.fit(X_train_std, Y_train)
predictions_knn = knn.predict(X_validation_std)
print(accuracy_score(Y_validation, predictions_knn))
print(confusion_matrix(Y_validation, predictions_knn))
print(classification_report(Y_validation, predictions_knn))

np.savetxt('ML_Data/traning.csv',X_train_std,fmt='%.2f',delimiter=',',header="'WC',	'Analytic',	'Clout',	'Authentic',	'Tone',	'WPS',	'Sixltr',	'Dic',	'function',	'pronoun',	'ppron',	'i',	'we',	'you',	'shehe',	'they',	'ipron',	'article',	'prep',	'auxverb',	'adverb',	'conj',	'negate',	'verb',	'adj',	'compare',	'interrog',	'number',	'quant',	'affect',	'posemo',	'negemo',	'anx',	'anger',	'sad',	'social',	'family',	'friend',	'female',	'male',	'cogproc',	'insight',	'cause',	'discrep',	'tentat',	'certain',	'differ',	'percept',	'see',	'hear',	'feel',	'bio',	'body',	'health',	'sexual',	'ingest',	'drives',	'affiliation',	'achieve',	'power',	'reward',	'risk',	'focuspast',	'focuspresent',	'focusfuture',	'relativ',	'motion',	'space',	'time',	'work',	'leisure',	'home',	'money',	'relig',	'death',	'informal',	'swear',	'netspeak',	'assent',	'nonflu',	'filler'")
np.savetxt('ML_Data/trainingLables.csv',Y_train,fmt='%s',delimiter=',', header=" #Class" )